/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
'use client'
import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
    const group = useRef()
    const { nodes, materials, shapes, animations } = useGLTF('/bunny-animations-applied2.glb')
    const { actions } = useAnimations(animations, group)
    const [sleep, setSleep] = useState(true)

    useEffect(() => {
        if (setSleep) {
            actions.Sleepy.play()
            actions.SleepyBunny.play()

        } else {
            actions.Sleepy.stop()
            actions.SleepyBunny.stop()
        }
    }, [sleep])

    const onClick = () => {
        setSleep(false)
        actions.Sleepy.stop()
        actions.SleepyBunny.stop()
        actions.Awaken.play()
        actions.AwakenBunny.play()
    }
    console.log(actions)
    // console.log(nodes, materials)
    return (
        <group ref={group} {...props} dispose={null} onClick={onClick}>
        <group name="Scene">
            <group name="Bunny_Soft_Toy" scale={6}>
            <group name="Bunny_Soft_Toy_Armature">
                <group name="Bunny_Soft_Toy001">
                <skinnedMesh
                    name="Cube003"
                    geometry={nodes.Cube003.geometry}
                    material={materials.cloth}
                    skeleton={nodes.Cube003.skeleton}
                    morphTargetDictionary={nodes.Cube003.morphTargetDictionary}
                    morphTargetInfluences={nodes.Cube003.morphTargetInfluences}
                />
                <skinnedMesh
                    name="Cube003_1"
                    geometry={nodes.Cube003_1.geometry}
                    material={materials.plastic}
                    skeleton={nodes.Cube003_1.skeleton}
                    morphTargetDictionary={nodes.Cube003_1.morphTargetDictionary}
                    morphTargetInfluences={nodes.Cube003_1.morphTargetInfluences}
                />
                <skinnedMesh
                    name="Cube003_2"
                    geometry={nodes.Cube003_2.geometry}
                    material={materials.light_cloth}
                    skeleton={nodes.Cube003_2.skeleton}
                    morphTargetDictionary={nodes.Cube003_2.morphTargetDictionary}
                    morphTargetInfluences={nodes.Cube003_2.morphTargetInfluences}
                />
                <skinnedMesh
                    name="Mouth"
                    geometry={nodes.Mouth.geometry}
                    material={materials.plastic}
                    skeleton={nodes.Mouth.skeleton}
                    morphTargetDictionary={nodes.Mouth.morphTargetDictionary}
                    morphTargetInfluences={nodes.Mouth.morphTargetInfluences}
                />
                <group name="Mouth001">
                    <skinnedMesh
                    name="Mouth_1"
                    geometry={nodes.Mouth_1.geometry}
                    material={materials.Mouth}
                    skeleton={nodes.Mouth_1.skeleton}
                    morphTargetDictionary={nodes.Mouth_1.morphTargetDictionary}
                    morphTargetInfluences={nodes.Mouth_1.morphTargetInfluences}
                    />
                    <skinnedMesh
                    name="Mouth_2"
                    geometry={nodes.Mouth_2.geometry}
                    material={materials.inside}
                    skeleton={nodes.Mouth_2.skeleton}
                    morphTargetDictionary={nodes.Mouth_2.morphTargetDictionary}
                    morphTargetInfluences={nodes.Mouth_2.morphTargetInfluences}
                    />
                </group>
                </group>
                <group name="Bunny_Soft_Toy002">
                <skinnedMesh
                    name="Cube004"
                    geometry={nodes.Cube004.geometry}
                    material={materials.plastic}
                    skeleton={nodes.Cube004.skeleton}
                    morphTargetDictionary={nodes.Cube004.morphTargetDictionary}
                    morphTargetInfluences={nodes.Cube004.morphTargetInfluences}
                />
                <skinnedMesh
                    name="Cube004_1"
                    geometry={nodes.Cube004_1.geometry}
                    material={materials.Eyes}
                    skeleton={nodes.Cube004_1.skeleton}
                    morphTargetDictionary={nodes.Cube004_1.morphTargetDictionary}
                    morphTargetInfluences={nodes.Cube004_1.morphTargetInfluences}
                />
                </group>
                <primitive object={nodes.body_3} />
            </group>
            </group>
        </group>
    </group>
    )
}

useGLTF.preload('/bunny-animations.glb')